import type { Locale, MissionCategory } from './types';

export type Copy = {
  hello: (name: string) => string; profile: string; nav: [string,string,string,string]; adTest: string;
  startPlan: string; guestTry: string; next: string; getAiPlan: string; planError: string;
  introPill: string; introTitleA: string; introTitleB: string; introDesc: string;
  mini: [[string,string],[string,string],[string,string]];
  basicTitle: string; basicDesc: string; nicknameLabel: string; nicknamePlaceholder: string; monthlyIncome: string;
  experience: string; beginner: string; some: string; experienced: string; language: string; market: string;
  skillsTitle: string; skillsSub: string; interestsTitle: string; interestsSub: string;
  goalTitle: string; goalDesc: string; targetIncome: string; weeklyHours: string; hours: (n:number)=>string; goalNotice: string;
  generatingTitleA: string; generatingTitleB: string; generatingDesc: string; generatingTime: string;
  monthlyGoal: string; current: string; recordIncome: string; incomePlaceholder: string; save: string; todayAction: string; completed: string;
  allDoneTitle: string; allDoneDesc: string; coach: string; upcoming: string; viewAll: string; minute: (n:number)=>string;
  streak: (n:number)=>string; streakDesc: string; missionTip: string; completeAction: string;
  recommended: string; fit: (n:number)=>string; firstRevenue: (n:number)=>string; milestones: string; alternatives: string;
  weeklyReport: string; progressTitle: string; executionRate: string; recordedIncome: string; actionStreak: string; completedActions: string;
  dayCount: (n:number)=>string; actionCount: (n:number)=>string; weeklyAnalysis: string; weeklyAnalysisDesc: string; rewardAd: string; betaMode: string;
  settingsTitle: string; once: string; lifetime: string; premiumDesc: string; storePrice: string; comingSoon: string;
  notification: string; notificationValue: string; aiCredits: string; aiCreditsValue: string; privacy: string; terms: string;
  resetConfirm: string; restart: string; version: string;
  categories: Record<MissionCategory,string>;
  skillLabels: Record<string,string>; interestLabels: Record<string,string>;
};

const commonSkills = {
  writing: ['글쓰기','Writing','文章作成','Escritura','Escrita'], design: ['디자인','Design','デザイン','Diseño','Design'], video: ['영상편집','Video editing','動画編集','Edición de video','Edição de vídeo'],
  sales: ['판매·영업','Sales','販売・営業','Ventas','Vendas'], consulting: ['상담','Consulting','相談','Consultoría','Consultoria'], spreadsheet: ['엑셀·스프레드시트','Spreadsheets','表計算','Hojas de cálculo','Planilhas'],
  development: ['개발','Development','開発','Desarrollo','Desenvolvimento'], social: ['SNS 운영','Social media','SNS運用','Redes sociales','Redes sociais'], research: ['정보검색','Research','情報検索','Investigación','Pesquisa'], living: ['요리·생활','Cooking & life skills','料理・生活','Cocina y vida práctica','Culinária e vida prática'],
};
const commonInterests = {
  content: ['블로그·콘텐츠','Content / blogging','ブログ・コンテンツ','Contenido / blogs','Conteúdo / blogs'], ecommerce: ['온라인 판매','Online selling','オンライン販売','Ventas online','Vendas online'], freelance: ['프리랜서','Freelancing','フリーランス','Freelance','Freelance'],
  digital: ['디지털 상품','Digital products','デジタル商品','Productos digitales','Produtos digitais'], affiliate: ['제휴마케팅','Affiliate marketing','アフィリエイト','Marketing de afiliados','Marketing de afiliados'], social: ['SNS','Social media','SNS','Redes sociales','Redes sociais'], local: ['지역 서비스','Local services','地域サービス','Servicios locales','Serviços locais'], coaching: ['교육·코칭','Teaching / coaching','教育・コーチング','Enseñanza / coaching','Ensino / coaching'],
};
const mapLabels = (index:number, source:Record<string,string[]>) => Object.fromEntries(Object.entries(source).map(([k,v])=>[k,v[index]]));

export const SKILL_IDS = Object.keys(commonSkills);
export const INTEREST_IDS = Object.keys(commonInterests);

export const COPY: Record<Locale, Copy> = {
  ko: {
    hello:n=>`안녕하세요, ${n}님`, profile:'프로필', nav:['오늘','계획','분석','설정'], adTest:'AdMob 테스트 배너', startPlan:'내 수익 계획 시작하기', guestTry:'가입 없이 먼저 체험할 수 있어요', next:'다음', getAiPlan:'AI에게 계획 받기', planError:'계획을 만들지 못했어요. 잠시 후 다시 시도해주세요.',
    introPill:'AI 수익 실행 플래너', introTitleA:'계획은 AI가.', introTitleB:'행동은 오늘부터.', introDesc:'내 경험과 시간에 맞는 수익 경로를 찾고, 매일 하나씩 실행해 보세요.', mini:[['맞춤 진단','나에게 맞는 수익모델'],['오늘의 행동','막막하지 않게 한 단계씩'],['성과 추적','실행과 수익을 한눈에']],
    basicTitle:'먼저, 당신을 알려주세요', basicDesc:'현실적으로 실행할 수 있는 계획을 만들게요.', nicknameLabel:'어떻게 불러드릴까요?', nicknamePlaceholder:'닉네임', monthlyIncome:'현재 월수입', experience:'현재 경험 수준', beginner:'처음 시작해요', some:'조금 해봤어요', experienced:'수익 경험이 있어요', language:'앱 언어', market:'활동할 국가/시장',
    skillsTitle:'이미 할 수 있는 일은?', skillsSub:'작은 경험도 좋아요. 여러 개 골라도 돼요.', interestsTitle:'어떤 방식에 관심 있나요?', interestsSub:'잘 모르겠다면 끌리는 것을 선택해 보세요.', goalTitle:'목표를 숫자로 정해볼까요?', goalDesc:'처음부터 완벽할 필요 없어요. 나중에 바꿀 수 있어요.', targetIncome:'한 달 목표수익', weeklyHours:'일주일에 사용할 수 있는 시간', hours:n=>`${n}시간`, goalNotice:'목표보다 중요한 건 매주 반복 가능한 행동이에요.',
    generatingTitleA:'당신에게 맞는', generatingTitleB:'수익 경로를 찾고 있어요', generatingDesc:'경험과 시간, 현지 시장을 분석해 오늘 시작할 행동으로 나누는 중이에요.', generatingTime:'잠시만 기다려주세요', monthlyGoal:'이번 달 수익 목표', current:'현재', recordIncome:'수익 기록 +', incomePlaceholder:'발생한 수익', save:'저장', todayAction:'오늘의 액션', completed:'완료', allDoneTitle:'이번 계획을 모두 완료했어요!', allDoneDesc:'잠시 쉬고 주간 분석을 받아보세요.', coach:'AI 코치의 한마디', upcoming:'다가오는 액션', viewAll:'전체보기', minute:n=>`${n}분`, streak:n=>`${n}일째 행동 중`, streakDesc:'작은 행동이 실제 수익을 만들어요.', missionTip:'완벽하게 끝내기보다 제한시간 안에 초안을 만드는 것이 목표예요.', completeAction:'액션 완료하기',
    recommended:'AI 추천 1순위', fit:n=>`${n}% 적합`, firstRevenue:n=>`첫 수익 약 ${n}일`, milestones:'90일 이정표', alternatives:'다른 가능성', weeklyReport:'WEEKLY REPORT', progressTitle:'행동이 쌓이고 있어요', executionRate:'실행률', recordedIncome:'기록 수익', actionStreak:'연속 행동', completedActions:'완료 액션', dayCount:n=>`${n}일`, actionCount:n=>`${n}개`, weeklyAnalysis:'AI 주간 분석', weeklyAnalysisDesc:'이번 주의 행동과 결과를 분석하고 다음 주 계획을 자동으로 조정해요.', rewardAd:'보상형 광고 보고 분석받기', betaMode:'베타에서는 테스트 모드로 제공됩니다',
    settingsTitle:'머니액션 설정', once:'한 번 결제로 평생', lifetime:'올인원 영구판', premiumDesc:'광고 제거 · 모든 플래너 기능 · AI 분석', storePrice:'스토어 현지가 적용', comingSoon:'준비 중', notification:'알림 시간', notificationValue:'오전 8:00', aiCredits:'AI 이용권', aiCreditsValue:'베타 제공', privacy:'개인정보처리방침', terms:'이용약관', resetConfirm:'모든 계획과 기록을 삭제할까요?', restart:'처음부터 다시 시작', version:'머니액션 베타 v0.1.1', categories:{prepare:'준비',build:'제작',customer:'고객',revenue:'수익'}, skillLabels:mapLabels(0,commonSkills), interestLabels:mapLabels(0,commonInterests),
  },
  en: {
    hello:n=>`Hi, ${n}`, profile:'Profile', nav:['Today','Plan','Insights','Settings'], adTest:'AdMob test banner', startPlan:'Build my income plan', guestTry:'Try it first — no sign-up required', next:'Next', getAiPlan:'Get my AI plan', planError:'We couldn’t build your plan. Please try again.',
    introPill:'AI Income Action Planner', introTitleA:'AI makes the plan.', introTitleB:'You take action today.', introDesc:'Find an income path that fits your skills and time, then move forward one action at a time.', mini:[['Personal match','Income ideas that fit you'],['One action today','Clear next step, no overwhelm'],['Track progress','See actions and income together']],
    basicTitle:'First, tell us about you', basicDesc:'We’ll build a plan you can realistically execute.', nicknameLabel:'What should we call you?', nicknamePlaceholder:'Name or nickname', monthlyIncome:'Current monthly income', experience:'Experience level', beginner:'Just starting', some:'I’ve tried a few things', experienced:'I’ve earned side income before', language:'App language', market:'Country / market',
    skillsTitle:'What can you already do?', skillsSub:'Small skills count. Pick as many as you like.', interestsTitle:'What kinds of income interest you?', interestsSub:'Not sure? Choose what sounds most appealing.', goalTitle:'Let’s put a number on the goal', goalDesc:'It doesn’t need to be perfect. You can change it later.', targetIncome:'Monthly income goal', weeklyHours:'Time available each week', hours:n=>`${n} hrs`, goalNotice:'Consistency matters more than a perfect target.',
    generatingTitleA:'Finding your best', generatingTitleB:'income paths', generatingDesc:'We’re matching your skills, time and local market to concrete actions you can start today.', generatingTime:'This should only take a moment', monthlyGoal:'This month’s income goal', current:'Current', recordIncome:'Log income +', incomePlaceholder:'Income earned', save:'Save', todayAction:'Today’s action', completed:'done', allDoneTitle:'You finished this plan!', allDoneDesc:'Take a moment, then review your weekly insights.', coach:'A note from your AI coach', upcoming:'Coming up', viewAll:'View all', minute:n=>`${n} min`, streak:n=>`${n}-day action streak`, streakDesc:'Small actions compound into real results.', missionTip:'The goal is a usable draft within the time limit, not perfection.', completeAction:'Mark action complete',
    recommended:'Top AI match', fit:n=>`${n}% fit`, firstRevenue:n=>`First revenue ~${n} days`, milestones:'90-day milestones', alternatives:'Other possibilities', weeklyReport:'WEEKLY REPORT', progressTitle:'Your actions are adding up', executionRate:'Execution rate', recordedIncome:'Income logged', actionStreak:'Action streak', completedActions:'Actions done', dayCount:n=>`${n} days`, actionCount:n=>`${n}`, weeklyAnalysis:'AI weekly analysis', weeklyAnalysisDesc:'Analyze this week’s actions and results, then adjust next week’s plan automatically.', rewardAd:'Watch a rewarded ad for analysis', betaMode:'Available in test mode during beta',
    settingsTitle:'MoneyAction settings', once:'One payment, lifetime access', lifetime:'All-in-one lifetime', premiumDesc:'No ads · full planner · AI analysis', storePrice:'Local store price', comingSoon:'Coming soon', notification:'Reminder time', notificationValue:'8:00 AM', aiCredits:'AI credits', aiCreditsValue:'Beta access', privacy:'Privacy policy', terms:'Terms of use', resetConfirm:'Delete all plans and records?', restart:'Start over', version:'MoneyAction beta v0.1.1', categories:{prepare:'Prepare',build:'Build',customer:'Customer',revenue:'Revenue'}, skillLabels:mapLabels(1,commonSkills), interestLabels:mapLabels(1,commonInterests),
  },
  ja: {
    hello:n=>`こんにちは、${n}さん`, profile:'プロフィール', nav:['今日','計画','分析','設定'], adTest:'AdMob テストバナー', startPlan:'収益プランを始める', guestTry:'登録なしで試せます', next:'次へ', getAiPlan:'AIプランを作る', planError:'プランを作成できませんでした。もう一度お試しください。',
    introPill:'AI収益アクションプランナー', introTitleA:'計画はAIに。', introTitleB:'行動は今日から。', introDesc:'経験と使える時間に合う収益ルートを見つけ、毎日ひとつずつ実行しましょう。', mini:[['個別診断','自分に合う収益モデル'],['今日の行動','迷わず一歩ずつ'],['進捗管理','行動と収益を見える化']],
    basicTitle:'まず、あなたについて教えてください', basicDesc:'無理なく実行できる計画を作ります。', nicknameLabel:'どうお呼びしますか？', nicknamePlaceholder:'ニックネーム', monthlyIncome:'現在の月収', experience:'経験レベル', beginner:'これから始める', some:'少し経験がある', experienced:'収益化経験がある', language:'アプリの言語', market:'活動する国・市場',
    skillsTitle:'今できることは？', skillsSub:'小さな経験でも大丈夫。複数選べます。', interestsTitle:'どんな方法に興味がありますか？', interestsSub:'迷ったら、気になるものを選んでください。', goalTitle:'目標を数字にしましょう', goalDesc:'完璧でなくて大丈夫。あとで変更できます。', targetIncome:'月の目標収益', weeklyHours:'週に使える時間', hours:n=>`${n}時間`, goalNotice:'目標額より、毎週続けられる行動が大切です。',
    generatingTitleA:'あなたに合う', generatingTitleB:'収益ルートを探しています', generatingDesc:'経験・時間・現地市場を分析し、今日から始められる行動に分解しています。', generatingTime:'少々お待ちください', monthlyGoal:'今月の収益目標', current:'現在', recordIncome:'収益を記録 +', incomePlaceholder:'発生した収益', save:'保存', todayAction:'今日のアクション', completed:'完了', allDoneTitle:'今回の計画をすべて完了しました！', allDoneDesc:'少し休んで、週間分析を確認しましょう。', coach:'AIコーチから一言', upcoming:'次のアクション', viewAll:'すべて見る', minute:n=>`${n}分`, streak:n=>`${n}日連続で行動中`, streakDesc:'小さな行動が実際の収益につながります。', missionTip:'完璧より、制限時間内に使える初稿を作ることが目標です。', completeAction:'アクション完了',
    recommended:'AIおすすめ1位', fit:n=>`適合度 ${n}%`, firstRevenue:n=>`初収益まで約${n}日`, milestones:'90日のマイルストーン', alternatives:'ほかの可能性', weeklyReport:'WEEKLY REPORT', progressTitle:'行動が積み上がっています', executionRate:'実行率', recordedIncome:'記録収益', actionStreak:'連続行動', completedActions:'完了アクション', dayCount:n=>`${n}日`, actionCount:n=>`${n}件`, weeklyAnalysis:'AI週間分析', weeklyAnalysisDesc:'今週の行動と結果を分析し、来週の計画を自動調整します。', rewardAd:'広告を見て分析する', betaMode:'ベータではテストモードです',
    settingsTitle:'MoneyAction 設定', once:'一度の購入でずっと使える', lifetime:'オールインワン永久版', premiumDesc:'広告なし・全プランナー機能・AI分析', storePrice:'ストアの現地価格', comingSoon:'準備中', notification:'通知時間', notificationValue:'午前8:00', aiCredits:'AI利用枠', aiCreditsValue:'ベータ提供', privacy:'プライバシーポリシー', terms:'利用規約', resetConfirm:'すべての計画と記録を削除しますか？', restart:'最初からやり直す', version:'MoneyAction beta v0.1.1', categories:{prepare:'準備',build:'作成',customer:'顧客',revenue:'収益'}, skillLabels:mapLabels(2,commonSkills), interestLabels:mapLabels(2,commonInterests),
  },
  es: {
    hello:n=>`Hola, ${n}`, profile:'Perfil', nav:['Hoy','Plan','Análisis','Ajustes'], adTest:'Banner de prueba AdMob', startPlan:'Crear mi plan de ingresos', guestTry:'Pruébalo sin registrarte', next:'Siguiente', getAiPlan:'Obtener mi plan con IA', planError:'No pudimos crear tu plan. Inténtalo de nuevo.',
    introPill:'Planificador de ingresos con IA', introTitleA:'La IA hace el plan.', introTitleB:'Tú actúas hoy.', introDesc:'Encuentra una ruta de ingresos acorde a tus habilidades y tiempo, y avanza una acción cada día.', mini:[['Diagnóstico personal','Modelos de ingreso para ti'],['Acción de hoy','Un paso claro cada vez'],['Seguimiento','Acciones e ingresos en un lugar']],
    basicTitle:'Primero, cuéntanos sobre ti', basicDesc:'Crearemos un plan que puedas ejecutar de verdad.', nicknameLabel:'¿Cómo quieres que te llamemos?', nicknamePlaceholder:'Nombre o apodo', monthlyIncome:'Ingreso mensual actual', experience:'Nivel de experiencia', beginner:'Estoy empezando', some:'Ya probé algunas cosas', experienced:'Ya he generado ingresos extra', language:'Idioma de la app', market:'País / mercado',
    skillsTitle:'¿Qué sabes hacer ya?', skillsSub:'Las habilidades pequeñas también cuentan. Elige varias.', interestsTitle:'¿Qué tipos de ingreso te interesan?', interestsSub:'Si no estás seguro, elige lo que más te atraiga.', goalTitle:'Ponle una cifra a tu objetivo', goalDesc:'No tiene que ser perfecto. Puedes cambiarlo después.', targetIncome:'Objetivo mensual', weeklyHours:'Tiempo disponible por semana', hours:n=>`${n} h`, goalNotice:'La constancia importa más que un objetivo perfecto.',
    generatingTitleA:'Buscando tus mejores', generatingTitleB:'rutas de ingreso', generatingDesc:'Analizamos tus habilidades, tiempo y mercado local para convertirlos en acciones concretas.', generatingTime:'Solo tomará un momento', monthlyGoal:'Objetivo de ingresos del mes', current:'Actual', recordIncome:'Registrar ingreso +', incomePlaceholder:'Ingreso obtenido', save:'Guardar', todayAction:'Acción de hoy', completed:'completadas', allDoneTitle:'¡Completaste este plan!', allDoneDesc:'Descansa un poco y revisa el análisis semanal.', coach:'Mensaje de tu coach IA', upcoming:'Próximas acciones', viewAll:'Ver todo', minute:n=>`${n} min`, streak:n=>`${n} días actuando`, streakDesc:'Las acciones pequeñas se convierten en resultados reales.', missionTip:'El objetivo es crear una primera versión útil dentro del tiempo, no perfección.', completeAction:'Marcar como completada',
    recommended:'Mejor opción según IA', fit:n=>`${n}% de ajuste`, firstRevenue:n=>`Primer ingreso ~${n} días`, milestones:'Hitos de 90 días', alternatives:'Otras posibilidades', weeklyReport:'WEEKLY REPORT', progressTitle:'Tus acciones se están acumulando', executionRate:'Tasa de ejecución', recordedIncome:'Ingresos registrados', actionStreak:'Racha de acción', completedActions:'Acciones completadas', dayCount:n=>`${n} días`, actionCount:n=>`${n}`, weeklyAnalysis:'Análisis semanal con IA', weeklyAnalysisDesc:'Analiza las acciones y resultados de la semana y ajusta automáticamente el próximo plan.', rewardAd:'Ver anuncio para obtener análisis', betaMode:'Disponible en modo de prueba durante la beta',
    settingsTitle:'Ajustes de MoneyAction', once:'Un pago, acceso de por vida', lifetime:'Versión completa de por vida', premiumDesc:'Sin anuncios · planificador completo · análisis IA', storePrice:'Precio local de la tienda', comingSoon:'Próximamente', notification:'Hora del recordatorio', notificationValue:'8:00', aiCredits:'Créditos IA', aiCreditsValue:'Acceso beta', privacy:'Política de privacidad', terms:'Términos de uso', resetConfirm:'¿Eliminar todos los planes y registros?', restart:'Empezar de nuevo', version:'MoneyAction beta v0.1.1', categories:{prepare:'Preparar',build:'Crear',customer:'Cliente',revenue:'Ingresos'}, skillLabels:mapLabels(3,commonSkills), interestLabels:mapLabels(3,commonInterests),
  },
  'pt-BR': {
    hello:n=>`Olá, ${n}`, profile:'Perfil', nav:['Hoje','Plano','Análises','Ajustes'], adTest:'Banner de teste AdMob', startPlan:'Criar meu plano de renda', guestTry:'Teste primeiro, sem cadastro', next:'Próximo', getAiPlan:'Receber meu plano com IA', planError:'Não conseguimos criar seu plano. Tente novamente.',
    introPill:'Planejador de renda com IA', introTitleA:'A IA faz o plano.', introTitleB:'Você age hoje.', introDesc:'Encontre uma rota de renda que combine com suas habilidades e tempo e avance uma ação por dia.', mini:[['Diagnóstico pessoal','Modelos de renda para você'],['Ação de hoje','Um passo claro por vez'],['Acompanhe o progresso','Ações e renda no mesmo lugar']],
    basicTitle:'Primeiro, conte sobre você', basicDesc:'Vamos criar um plano que você consiga executar de verdade.', nicknameLabel:'Como devemos chamar você?', nicknamePlaceholder:'Nome ou apelido', monthlyIncome:'Renda mensal atual', experience:'Nível de experiência', beginner:'Estou começando', some:'Já tentei algumas coisas', experienced:'Já tive renda extra', language:'Idioma do app', market:'País / mercado',
    skillsTitle:'O que você já sabe fazer?', skillsSub:'Pequenas habilidades também contam. Escolha várias.', interestsTitle:'Que tipos de renda interessam você?', interestsSub:'Se não souber, escolha o que parece mais atraente.', goalTitle:'Vamos definir uma meta', goalDesc:'Não precisa ser perfeita. Você pode mudar depois.', targetIncome:'Meta mensal de renda', weeklyHours:'Tempo disponível por semana', hours:n=>`${n} h`, goalNotice:'Consistência importa mais que uma meta perfeita.',
    generatingTitleA:'Buscando suas melhores', generatingTitleB:'rotas de renda', generatingDesc:'Analisamos habilidades, tempo e mercado local para criar ações concretas para começar hoje.', generatingTime:'Isso deve levar só um momento', monthlyGoal:'Meta de renda deste mês', current:'Atual', recordIncome:'Registrar renda +', incomePlaceholder:'Renda obtida', save:'Salvar', todayAction:'Ação de hoje', completed:'concluídas', allDoneTitle:'Você concluiu este plano!', allDoneDesc:'Faça uma pausa e veja sua análise semanal.', coach:'Mensagem do seu coach de IA', upcoming:'Próximas ações', viewAll:'Ver tudo', minute:n=>`${n} min`, streak:n=>`${n} dias de ação`, streakDesc:'Pequenas ações se transformam em resultados reais.', missionTip:'A meta é criar uma primeira versão útil dentro do tempo, não buscar perfeição.', completeAction:'Marcar como concluída',
    recommended:'Melhor opção da IA', fit:n=>`${n}% de compatibilidade`, firstRevenue:n=>`Primeira renda ~${n} dias`, milestones:'Marcos de 90 dias', alternatives:'Outras possibilidades', weeklyReport:'WEEKLY REPORT', progressTitle:'Suas ações estão se acumulando', executionRate:'Taxa de execução', recordedIncome:'Renda registrada', actionStreak:'Sequência de ação', completedActions:'Ações concluídas', dayCount:n=>`${n} dias`, actionCount:n=>`${n}`, weeklyAnalysis:'Análise semanal com IA', weeklyAnalysisDesc:'Analise as ações e resultados da semana e ajuste automaticamente o plano da próxima semana.', rewardAd:'Ver anúncio para receber análise', betaMode:'Disponível em modo de teste durante a beta',
    settingsTitle:'Ajustes do MoneyAction', once:'Um pagamento, acesso vitalício', lifetime:'Versão completa vitalícia', premiumDesc:'Sem anúncios · planejador completo · análise IA', storePrice:'Preço local da loja', comingSoon:'Em breve', notification:'Horário do lembrete', notificationValue:'8:00', aiCredits:'Créditos de IA', aiCreditsValue:'Acesso beta', privacy:'Política de privacidade', terms:'Termos de uso', resetConfirm:'Excluir todos os planos e registros?', restart:'Começar de novo', version:'MoneyAction beta v0.1.1', categories:{prepare:'Preparar',build:'Criar',customer:'Cliente',revenue:'Renda'}, skillLabels:mapLabels(4,commonSkills), interestLabels:mapLabels(4,commonInterests),
  },
};

export const LANGUAGE_NAMES: Record<Locale,string> = { ko:'한국어', en:'English', ja:'日本語', es:'Español', 'pt-BR':'Português (Brasil)' };
